<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>



<ol style="display: none;" class="<?php echo $this->getName()?>" <?php if ($this->getCollapsed() && !$this->getHasSelection()): ?>class="no-display-current" <?php endif ?>>
<?php
switch ($this->getDisplayType()){
    case Amasty_Shopby_Model_Source_Attribute::DT_LABELS_ONLY:
        if ($this->getShowSearch()){
            echo '<li rel="search"><input type="text" class="amshopby_attr_search input-text" onkeyup="amshopby_attr_search(this)" /></li>';
        }
        foreach ($this->getItemsAsArray() as $item){
            echo '<li '.(isset($item['style']) ? $item['style'] : '').' data-text="' . htmlspecialchars($item['label']) . '"><a class="'.$item['css'].'"' . $item['rel'] . ' href="'.$item['url'].'">'. $item['label'] . $item['count'] . '</a>' . '</li>';
        }
    break;
    
    case Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_ONLY:
        echo '<li>';
        foreach ($this->getItemsAsArray() as $item){
            if (isset($item['image_hover']) && $item['image_hover'] != '') {
                echo '<img src="' . $item['image_hover'] . '" style="display: none;" />';
                $onHover = 'onmouseover=this.src="' . $item['image_hover'] . '"'; 
                $onHover .= ' onmouseout=this.src="' . $item['image'] . '"';
            } else {
                $onHover = '';
            }
            echo '<a '.$item['style'].$item['rel'].' class="'.$item['css'].'" href="'.$item['url'].'"><img src="'.$item['image'].'" ' . $onHover . ' title="'. $item['label'] .'" alt="'. $item['label'] .'"></a>';
            
        }
        echo '</li>';
    break;
    
    case Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_AND_LABELS:
        if ($this->getShowSearch()){
            echo '<li rel="search"><input type="text" class="amshopby_attr_search" onkeyup="amshopby_attr_search(this)" /></li>';
        }
        foreach ($this->getItemsAsArray() as $item){
            echo '<li '.$item['style'].' data-text="' . htmlspecialchars($item['label']) . '"><a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'">';
            
            if (isset($item['image_hover']) && $item['image_hover'] != '') {
                echo '<img src="' . $item['image_hover'] . '" style="display: none;" />';
                $onHover = 'onmouseover=this.src="' . $item['image_hover'] . '"'; 
                $onHover .= ' onmouseout=this.src="' . $item['image'] . '"';
            } else {
                $onHover = '';
            }
            
            if (!empty($item['image'])){
                echo '<img src="'.$item['image'].'" ' . $onHover . ' title="'. $item['label'] .'" alt="'. $item['label'] .'">';
            }
            echo $item['label'] . $item['count'] . '</a>' . '</li>';
        }
    break;
    
    case Amasty_Shopby_Model_Source_Attribute::DT_DROPDOWN:
        echo '<li><select onchange="if (this.value) setLocation(this.value)" class="amshopby-select amshopby-ajax-select">';
        echo '<option value="">' . $this->getName() . '&nbsp; &#43;</option>';
        //echo '<option value="'.$this->getRemoveUrl().'">&nbsp;</option>';
        foreach ($this->getItemsAsArray() as $item){
            echo '<option '.$item['css'] . $item['rel'] . ' value="'.$item['url'].'">'. $item['label'] . $item['count'] . '</option>';
        }
        echo '</select></li>';
    break;
    
    case Amasty_Shopby_Model_Source_Attribute::DT_LABELS_IN_2_COLUMNS:
        $items = $this->getItemsAsArray(); 
        $size  = sizeof($items);
        $half  =  ceil($size/2);
        
        echo '<li>';
        echo '<div class="amshopby-column">';
        for ($i=0; $i<$half; $i++){
            $item = $items[$i];
            echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars($item['label']) . '">'. $item['label'] . $item['count'] . '</a>' . '<br/>';
        }
        echo '</div>';
        echo '<div class="amshopby-column">';
        for ($i=$half; $i<$size; $i++){
            $item = $items[$i];
            echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars($item['label']) . '">'. $item['label'] . $item['count'] . '</a>' . '<br/>';
        }
        echo '</div>';
        echo '</li>';
    break;
}

if ($this->getShowLessMore() && in_array($this->getDisplayType(), array(
        Amasty_Shopby_Model_Source_Attribute::DT_LABELS_ONLY,
        Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_ONLY,
        Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_AND_LABELS,
    ))) {

    $total = count($this->getItemsAsArray());
    $short = $this->getMaxOptions();
    $add = $total - $short;
    if ($add > 0) {
        $text = sprintf($this->__('View %d More'), $add);
        echo '<li class="amshopby-clearer"><a id="amshopby-more-'.$this->getRequestValue().'" class="amshopby-more" href="#">' . $text . '</a></li>';
    }
    echo '<li class="amshopby-clearer"><a id="amshopby-less-'.$this->getRequestValue().'" class="amshopby-less" href="#" style="display:none">' . $this->__('Show Less') . '</a></li>';
}
?>





</ol>

<script type="text/javascript">

    jQuery(function($) {
        $(document).ready(function() {
            //if ($(window).width() > 768) {

                if ($('#Size').length) {
                    $('#Size').click(function (e) {
                        //console.log('size');
                        e.stopImmediatePropagation();
                        if ($('.Size').is(':visible')) {
                            $('.Size').hide();
                        } else {
                            $('.Size').show();
                            $('.Occasion').hide();
                            $('.Color').hide();
                        }
                        return false;
                    });
                }
                if ($('#Color').length) {
                    $('#Color').click(function (e) {
                        e.stopImmediatePropagation();
                        if ($('.Color').is(':visible')) {
                            $('.Color').hide();
                        } else {
                            $('.Color').show();
                            $('.Occasion').hide();
                            $('.Size').hide();
                        }
                    });
                }
                if ($('#Occasion').length) {
                    $('#Occasion').click(function (e) {
                        e.stopImmediatePropagation();
                        if ($('.Occasion').is(':visible')) {
                            $('.Occasion').hide();
                        } else {
                            $('.Occasion').show();
                            $('.Color').hide();
                            $('.Size').hide();
                        }
                    });
                }
            //}
            if (window.matchMedia('(max-width: 768px)').matches) {
                $('.filter-toggle-content').hide();
            }
            else {
                if ($('#action-status').height() == 0) {

                    $('.category-products .pager').first().css('border-top', 'none');
                }
                else {
                    $('.category-products .pager').first().css('border-top', '1px solid #D3D2D8');
                }
            }

            $('#filter-block').off().click(function() {
                //console.log($(window).width() );
                if (!window.matchMedia('(max-width: 768px)').matches) {
                    return;
                } else {
                    if (!$(this).hasClass('active-filter')) {
                        $(this).addClass('active-filter');
                        $('.filter-toggle-content').show();
                        $('.category-products .toolbar').first().css('border-bottom', '1px solid #D3D2D8');
                    }
                    else {
                        $(this).removeClass('active-filter');
                        $('.filter-toggle-content').hide();
                        $('.category-products .toolbar').first().css('border-bottom', 'none');
                    }
                }

            });

            $(window).resize(function() {
                $('#filter-block').removeClass('active-filter');
                if (!window.matchMedia('(max-width: 768px)').matches) {
                    //console.log('>768');
                    $('.filter-toggle-content').show();
                    $('#filter-content').appendTo('#filter-wrapper');

                    //border between page and filter

                    if ($('#action-status').height() == 0) {

                        $('.category-products .pager').first().css('border-top', 'none');
                    }
                    else {
                        $('.category-products .pager').first().css('border-top', '1px solid #D3D2D8');
                    }

                    $('.category-products .toolbar').first().css('border-bottom', '1px solid #D3D2D8');

                }
                else {
                    $('.filter-toggle-content').hide();
                    //$('#filter-content').after('#filter-wrapper');

                    $('.category-products .pager').first().css('border-top', '1px solid #D3D2D8');

                    $('.category-products .toolbar').first().css('border-bottom', 'none');
                }
            });

        });
    });

</script>