<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
</div>
<?php if($this->canShowBlock()): ?>

    <div id="filter-block" class="block block-layered-nav">




        <!--<div id="filter-block">-->
      <!--  <div class="block-title">
            <div class="filterby"><strong><span><?php echo $this->__('Filter by:') ?></span></strong></div>
        </div>
    </div>-->


        <div class="block-title">
            <div class="filterby"><strong><span><?php echo $this->__('Filter by:') ?></span></strong></div>
        </div>


        <div id='filter-wrapper' class="block-content filter-toggle-content filter-wrapper">


        <!--<div class="filterby"><strong><span><?php echo $this->__('Filter by:') ?></span></strong></div>-->
        <!--
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                <div class="actions"><a href="<?php echo Mage::helper('amshopby/url')->getFullUrl(array(), 1) ?>">
                        <?php echo Mage::helper('catalog')->__('Clear All') ?></a>
                </div>
            <?php endif; ?>
        -->


            <?php if($this->canShowOptions()): ?>
                    <div id="filter-content" class="filter-content amshopby-container-top block-layered-nav filter-toggle-content">
                        <?php foreach ($this->getFilters() as $_filter): ?>
                            <?php if($_filter->getItemsCount()): ?>
                                <?php  $position = Mage::helper('amshopby')->getAttributePosition($_filter); ?>
                                <div class="amshopby-item-top block-content am-toggle-content">
                                    <dl id="narrow-by-list" class="amshopby-narrow-by-list" data-position="<?php echo $position;?>">
                                        <?php if ($_filter->getAttributeCode() == 'price') : ?>
                                            <?php $_filter->addData(array('amprice-position' => 'top')); ?>
                                        <?php endif; ?>
                                        <dt id="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
                                        <dd style="background:none"><?php echo $_filter->getHtml() ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <?php endif; ?>

            <div id="action-status">
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                            <div class="actions"><a href="<?php echo Mage::helper('amshopby/url')->getFullUrl(array(), 1) ?>">
                                    <?php echo Mage::helper('catalog')->__('Clear All') ?></a>
                            </div>
                        <?php endif; ?>
            <?php echo $this->getStateHtml() ?>
            </div>

        </div>





        <!--</div>-->
  </div>
<?php else: ?>
    <div style="display:none" class="<?php echo $this->getBlockId()?>"></div>
<?php endif; ?>
</div>



